Repository bsoc-bitbyte/busify, pull requests merged in 2023-07, with the labels that each got.

#53 feat(Frontend): Added the manage buses button
  frontend/src/components/Navbar/index.tsx
  frontend/src/store/authStore.tsx
Labels: difficulty - easy

#55 feat(Frontend): Added the AdminSideBar component
  frontend/src/components/AdminSideBar/index.tsx
Labels: difficulty - medium

#54 feat(frontend): Add UserProtected Route
  frontend/src/App.tsx
  frontend/src/components/BusDetails/index.tsx
  frontend/src/components/ProtectedRoutes.tsx
  frontend/src/components/ValidateAuth.tsx
  frontend/src/pages/DemoPage/demopage.tsx
  frontend/src/store/authStore.tsx
Labels: difficulty - hard

#46 Feat(frontend): Created checkout page
  frontend/src/App.tsx
  frontend/src/components/BusDetails/index.tsx
  frontend/src/components/BusDetailsCard/index.tsx
  frontend/src/components/BusTicket/index.tsx
  frontend/src/components/FareBreakdownCard/index.tsx
  frontend/src/pages/BusSchedule/index.tsx
  frontend/src/pages/Checkout/index.tsx
  frontend/src/store/orderStore.tsx
  frontend/src/types.d.ts
Labels: difficulty - hard

#61 Fix(Frontend): Removed the rupee symbol and changed the Net amount to…
  frontend/src/components/FareBreakdownCard/index.tsx
Labels: difficulty - easy

#45 feat: Made HeroContainer component responsive
  frontend/src/pages/Home/index.tsx
Labels: difficulty - easy

#66 feat: Replace 'Write Passengers Roll no' with 'Write passengers EmaiID
  frontend/src/components/BusDetails/index.tsx
  frontend/src/pages/Checkout/index.tsx
  frontend/src/store/orderStore.tsx
Labels: difficulty - easy
