Repository bsoc-bitbyte/busify, pull requests merged in 2023-06, with the labels that each got.

#13 feat(frontend): Added footer
  frontend/src/assets/iiitdmj-logo.jpg
  frontend/src/assets/iiitdmj-logo.svg
  frontend/src/components/Footer/footer.tsx
  frontend/src/components/Footer/index.tsx
  frontend/src/pages/home/index.tsx
Labels: difficulty - easy

#17 feat(Frontend): Added general button component
  frontend/src/components/CustomButton/index.tsx
  frontend/src/types.d.ts
Labels: discussion

#22 New home section
  frontend/src/App.tsx
  frontend/src/assets/bgimg.png
  frontend/src/assets/bus.png
  frontend/src/assets/person.png
  frontend/src/assets/ticket.png
  frontend/src/pages/home/home.module.scss
  frontend/src/pages/home/index.tsx
Labels: difficulty - easy

#23 refactor: Remodify BusTicket component
  frontend/src/components/BusTicket/index.tsx
  frontend/src/components/BusTicket/ticketData.tsx
Labels: difficulty - medium

#27 Styled the default scrollbar
  frontend/src/index.css
Labels: difficulty - easy

#32 feat(index): Change index.html file
  frontend/index.html
Labels: difficulty - easy

#33 feat(frontend): Add error toast for unauthorized tickect booking
  frontend/package.json
  frontend/src/components/BusTicket/index.tsx
Labels: difficulty - easy
