Repository bsoc-bitbyte/busify, pull requests merged in 2024-07, with the labels that each got.

#93 feat(ticket-page): implement dynamic cards for ticket page #88
  backend/prisma/seed.mjs
  backend/src/ticket/ticket.controller.ts
  backend/src/ticket/ticket.service.ts
  frontend/src/components/BusDetails/index.tsx
  frontend/src/components/BusTicket/index.tsx
  frontend/src/components/TicketCard.tsx
  frontend/src/components/TicketCardClose.tsx
  frontend/src/pages/Profile/index.tsx
  frontend/src/types.d.ts
Labels: difficulty - hard, bsoc’24

#97 feat(encryption and decryption): added backend routes for ticket encryption and decryption
  backend/package-lock.json
  backend/package.json
  backend/prisma/schema.prisma
  backend/prisma/seed.mjs
  backend/src/app.module.ts
  backend/src/ticket/ticket.service.ts
  backend/src/ticketScanner/ticket-scanner.controller.ts
  backend/src/ticketScanner/ticket-scanner.module.ts
  backend/src/ticketScanner/ticket-scanner.service.ts
  frontend/src/components/TicketCard.tsx
  frontend/src/pages/DemoPage/demopage.tsx
  frontend/src/types.d.ts
Labels: difficulty - hard, BSoC'24

#96 fix #94 : Adds capabilities to create and update schedules.
  backend/src/Bus/bus.controller.ts
  backend/src/Bus/bus.service.ts
  backend/src/Bus/dto/index.ts
  backend/src/Orders/orders.controller.ts
  backend/src/Orders/orders.service.ts
  backend/src/Redis/redis.service.ts
  backend/src/ticket/ticket.service.ts
  frontend/public/marker.svg
  frontend/src/components/AdminPanel/AdminSideBar/index.tsx
  frontend/src/components/AdminPanel/EditBusDetailsModal/index.tsx
  frontend/src/components/AdminPanel/OrderDetailsCard/index.tsx
  frontend/src/components/AdminPanel/RecentOrderCard/index.tsx
  frontend/src/components/DetailsCards/BusCards/index.tsx
  frontend/src/pages/AdminDashBoard/index.tsx
  frontend/src/pages/AdminSchedule/index.tsx
  frontend/src/types.d.ts
Labels: difficulty - hard, BSoC'24

#104 fix: created footer and pricing page layout
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/Footer/index.tsx
  frontend/src/pages/PricingPage/PricingCards.tsx
  frontend/src/pages/PricingPage/PricingPage.tsx
Labels: difficulty - medium, BSoC'24

#102 feat(frontend): added custom empty modal
  backend/.husky/commit-msg
  backend/.husky/pre-commit
  backend/package-lock.json
  backend/src/app.module.ts
  frontend/src/App.tsx
  frontend/src/assets/NoPage.svg
  frontend/src/assets/NotFound.svg
  frontend/src/components/Custom Empty Modal/index.tsx
  frontend/src/components/TicketCard.tsx
  frontend/src/components/TicketCardClose.tsx
  frontend/src/pages/AdminDashBoard/index.tsx
  frontend/src/pages/AdminSchedule/index.tsx
  frontend/src/pages/NotFoundPage/index.tsx
  frontend/src/pages/Profile/index.tsx
  frontend/src/types.d.ts
Labels: difficulty - medium, BSoC'24

#109 fix: Create Policy and terms Pages
  backend/package-lock.json
  backend/package.json
  frontend/src/App.tsx
  frontend/src/assets/termsAndPolicy_1.avif
  frontend/src/assets/termsAndPolicy_2.avif
  frontend/src/assets/termsAndPolicy_3.jpg
  frontend/src/components/Footer/index.tsx
  frontend/src/pages/PrivacyPolicy/PrivacyPolicy.tsx
  frontend/src/pages/RefundPolicy/RefundPolicy.tsx
  frontend/src/pages/TermsAndconditions/TermsAndConditions.tsx
Labels: difficulty - easy, BSoC'24

#111 feat(About) made an aboutus page
  frontend/src/App.tsx
  frontend/src/assets/about-us.png
  frontend/src/assets/our-mission.jpg
  frontend/src/assets/our-story.jpg
  frontend/src/components/Footer/index.tsx
  frontend/src/pages/AboutUs/AboutUs.tsx
Labels: difficulty - easy, BSoC'24
