Repository bsoc-bitbyte/busify, pull requests merged in 2024-06, with the labels that each got.

#80 Fix #76 :Responsiveness of BusDetails Card component
  frontend/src/components/BusDetailsCard/index.tsx
Labels: bug, frontend, work in progress

#77 Fix #75: Added an admin page layout
  frontend/src/App.tsx
  frontend/src/components/AdminPanel/AdminLayout/index.tsx
  frontend/src/components/Navbar/index.tsx
  frontend/src/pages/Admin/index.tsx
  frontend/src/types.d.ts
Labels: work in progress, difficulty - medium

#79 docs(contributing): update issue guidelines
  Contributing.md
Labels: documentation

#83 feat(frontend): Added responsive profile page layout
  frontend/src/App.tsx
  frontend/src/components/Navbar/index.tsx
  frontend/src/pages/Profile/animation.css
  frontend/src/pages/Profile/index.tsx
Labels: difficulty - medium

#87 feat(frontend): added admin protected routes
  frontend/src/App.tsx
  frontend/src/components/AdminProtectedRoutes.tsx
  frontend/src/pages/AdminDashBoard/index.tsx
Labels: difficulty - easy

#91 feat(frontend): added admin schedule page
  frontend/src/App.tsx
  frontend/src/components/AdminPanel/AdminSideBar/index.tsx
  frontend/src/components/DetailsCards/BusCards/index.tsx
  frontend/src/components/DetailsCards/ConductorCards/index.tsx
  frontend/src/components/TicketCard.tsx
  frontend/src/components/TicketCardClose.tsx
  frontend/src/pages/AdminDashBoard/index.tsx
  frontend/src/pages/AdminSchedule/index.tsx
  frontend/src/store/tabStore.tsx
Labels: difficulty - medium
